### PR TITLE
Some changes

### PR DESCRIPTION
**Pull request by igogo5yo**
I removed  one hard-code style attribute, added i18n support and translated to ru

### CODE REVIEW

**Comment by igogo5yo** [comment]
For tests have been performed, you need add the following code to config - 
```php
'i18n' => [
      'translations' => [
          'file-input*' => [
              'class' => 'yii\i18n\PhpMessageSource',
              'basePath' => dirname(__FILE__).'/../vendor/2amigos/yii2-file-input-widget/src/messages/',
          ],
      ],
  ],
```

**Comment by tonydspaniard** [comment]
@igogo5yo sorry for the late reply. I would like to merge your changes... do you mind fixing the conflicts? Thank you very much in advance.

**Comment by tonydspaniard** [comment]
@igogo5yo  no need... i am adding all your changes my self

**Comment by tonydspaniard** [comment]
added your changes with new version. thank you very much @igogo5yo

**Pull request closed without merging**
